spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/srs_db
    username: ilya
    password: srs_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080