services:
  postgres:
    image: postgres:17
    container_name: srs-postgres
    environment:
      POSTGRES_DB: srs_db
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: srs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: